export const SECTORS = [
  "IT – Software",
  "IT – Hardware",
  "Artificial Intelligence",
  "Data Engineering",
  "Biotechnology",
  "Aerospace",
  "Civil Engineering",
  "Finance",
  "Healthcare",
  "Manufacturing",
  "Education",
  "Research",
  "Law",
  "Certifications",
  "Other"
];

export const SKILLSETS_BY_SECTOR = {
  "IT – Software": ["Java", "Python", "React", "Node.js", "TypeScript", "C++", "C#", "Go", "Rust", "Swift", "Kotlin", "PHP", "Ruby on Rails", "Angular", "Vue.js", "Docker", "Kubernetes", "AWS", "Azure", "GCP", "SQL", "NoSQL", "Git", "Jenkins", "CI/CD"],
  "IT – Hardware": ["Computer Architecture", "VLSI", "Embedded Systems", "Microcontrollers", "FPGA", "PCB Design", "Digital Logic", "Analog Circuits", "Robotics", "Network Engineering", "Cisco CCNA", "CompTIA A+"],
  "Artificial Intelligence": ["Machine Learning", "Deep Learning", "Natural Language Processing", "Computer Vision", "Reinforcement Learning", "PyTorch", "TensorFlow", "Scikit-learn", "Generative AI", "LLMs", "Prompt Engineering"],
  "Data Engineering": ["Snowflake", "Apache Spark", "Hadoop", "Kafka", "ETL Pipelines", "Data Warehousing", "BigQuery", "Redshift", "Airflow", "Databricks", "dbt"],
  "Biotechnology": ["Molecular Biology", "Genetics", "Bioinformatics", "CRISPR", "Biochemistry", "Microbiology", "Clinical Research", "Pharmacology", "Bioprocess Engineering"],
  "Aerospace": ["Aerodynamics", "Propulsion", "Orbital Mechanics", "Avionics", "Aerospace Materials", "CFD", "Satellite Communications", "Flight Dynamics"],
  "Civil Engineering": ["Structural Analysis", "Geotechnical Engineering", "Transportation Engineering", "Hydraulics", "AutoCAD", "Revit", "Construction Management", "Surveying"],
  "Finance": ["Chartered Accountancy", "Investment Banking", "Financial Modeling", "Risk Management", "Corporate Finance", "Portfolio Management", "Derivatives", "Fintech", "Blockchain"],
  "Healthcare": ["Nursing", "Medical Coding", "Radiology", "Health Informatics", "Patient Care", "Epidemiology", "Telemedicine", "Healthcare Administration"],
  "Manufacturing": ["Six Sigma", "Lean Manufacturing", "Supply Chain Management", "Industrial Engineering", "Quality Control", "PLC Programming", "CAD/CAM", "Operations Management"],
  "Education": ["Curriculum Development", "Instructional Design", "Educational Technology", "Special Education", "Pedagogy", "E-learning", "Academic Research"],
  "Research": ["Scientific Writing", "Statistical Analysis", "R Programming", "Experimental Design", "Grant Writing", "Data Visualization", "Qualitative Research"],
  "Law": ["Corporate Law", "Intellectual Property", "Litigation", "Criminal Law", "Contract Law", "Legal Research", "Compliance", "International Law"],
  "Certifications": [
    "AWS Certified Solutions Architect",
    "AWS Certified Developer",
    "AWS Certified SysOps Administrator",
    "AWS Certified DevOps Engineer",
    "AWS Certified Security",
    "Azure Fundamentals",
    "Azure Solutions Architect Expert",
    "Azure Administrator Associate",
    "Google Cloud Professional Cloud Architect",
    "Google Cloud Professional Data Engineer",
    "CompTIA A+",
    "CompTIA Network+",
    "CompTIA Security+",
    "CompTIA Cloud+",
    "Cisco CCNA",
    "Cisco CCNP",
    "Cisco CCIE",
    "Certified Information Systems Security Professional (CISSP)",
    "Certified Ethical Hacker (CEH)",
    "Certified Information Security Manager (CISM)",
    "Project Management Professional (PMP)",
    "Certified ScrumMaster (CSM)",
    "Certified Scrum Product Owner (CSPO)",
    "ITIL Foundation",
    "Salesforce Certified Administrator",
    "Salesforce Certified Platform Developer",
    "Oracle Certified Professional",
    "Red Hat Certified System Administrator (RHCSA)",
    "Red Hat Certified Engineer (RHCE)",
    "VCP-DCV (VMware Certified Professional)",
    "CFA (Chartered Financial Analyst)",
    "CPA (Certified Public Accountant)",
    "SHRM-CP (Society for Human Resource Management)",
    "Six Sigma Green Belt",
    "Six Sigma Black Belt"
  ]
};

export const GLOBAL_SKILLSETS = Object.values(SKILLSETS_BY_SECTOR).flat();
